// General Item properties
const ITEM_OPACITY = 0



/// Fonts Settings
const FONT_MATERIAL_DESIGN = "Material Icons"
const ICON_DEFAULT_COLOR = "#FFF"
const ICON_ACTIVE_COLOR = "red"


const FONT_HEADER_MEDUIM= "Roboto Lite"
const FONT_HEADER_MEDUIM_SIZE = 14
const FONT_HEADER_LARGE= "Roboto"
const FONT_HEADER_LARGE_SIZE = 24
const FONT_HEADER_LARGE_COLOR = "#888"

const SIDE_BAR_COLOR = "#7264A7"

const CART_WIDTH = 150
const CART_HEIGHT = 200
const CART_MARGINS = 30
const CART_ROUNDED_CORNERS = 10
const CART_SHADOW_OFFSET = 0
const CART_SHADOW_OFFSET_HOVERED = 6
const CART_OPACITY = 0.3

const TOP_LIST_HEIGHT = 150
const TOP_LIST_ITEM_WIDTH = 100

// Actions.
const MOUSE_HOVER = "MOUSE_HOVER"
const MOUSE_OUT = "MOUSE_OUT"
const LEFT_MOUSE_CLICK = "LEFT_MOUSE_CLICK"
const LEFT_MOUSE_DOUBLE_CLICK = "LEFT_MOUSE_DOUBLE_CLICK"
const LEFT_MOUSE_RELEASE = "LEFT_MOUSE_RELEASE"
const LEFT_MOUSE_HOLD = "LEFT_MOUSE_HOLD"
